### ISSUE TITLE
HS410 Switcher connection dropout

### ISSUE THREAD

**Issue by davidadevore** [bitfocus/companion-module-panasonic-avhs#1]
Using 1.2.0-85393af-1109
**Describe the bug**
Connection to HS 410 drops for 3 seconds. Drops occur every 10-15 seconds. Network is a small netgear switch with just computer and switcher. When the connection is active, the commands work and control the switcher just fine. All commands that I have tried work great! 

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6 
 - Browser: Chrome

**Comment by JeffreyDavidsz** [comment]
Can we close this @haakonnessjoen ?

**Comment by PTGitHubber** [comment]
Has this been looked at? I have stopped using Companion with the AVHS 410 in show for this very reason, after experiencing it multiple times myself.

**Comment by JeffreyDavidsz** [comment]
We might put a stay alive command in, if nothing happens for 5 seconds send something.

**Comment by JeffreyDavidsz** [comment]
mmmm looks like @haakonnessjoen allready put some check in for that;
`
if (self.config.model == 'HS410') {
	self.udptimer = setInterval(function () {
	    self.sendUDPCommand('SPAT:0:00');
	}, 500);
}`

**Comment by PTGitHubber** [comment]
Ah. I'll test this on Monday, then. I'll be around an AVHS410, and postmy findings here.

**Comment by haakonnessjoen** [comment]
Hah, can’t even remember doing that. And I see I forgot to clear the timer in destroy too :/

**Comment by PTGitHubber** [comment]
I tested on the latest bleeding edge build just now, and the dropout is still happening. It's only if the connection is idle for approximately 8 seconds, and if you try to send a command while the connection is resetting, nothing happens.

**Comment by stmoss** [comment]
Following up here, I am having the same problem...

**Comment by McHauge** [comment]
Got a unit with the same thing happening in 2020 too.

**Comment by thedmo** [comment]
I noticed this to happen on a Browser too. When using the Commands with OSC everything seemed to work nicely though.

**Comment by stmoss** [comment]
OSC?

**Comment by thedmo** [comment]
Last time i controled Companion with OSC Commands out of QLab, i could control the switcher in these moments, when in a my browser there was no Connection. I used it with Safari.

**Comment by McHauge** [comment]
@haakonnessjoen, @stmoss, @thedmo, I think I found the bug, it seems to work now without disconnecting in my dev builds :)

**Comment by McHauge** [comment]
I'll post a fix within a week or so.

**Comment by McHauge** [comment]
This should be fixed in the next version of the module (V1.0.2), I'll close this for now, please feel free to open it up again if need be.

**Comment by stmoss** [comment]
Thanks!


Steve Moss
Director, Technical Services

FMP | 3600 Horizon Drive, Suite 180<x-apple-data-detectors://3> |<x-apple-data-detectors://3>King<x-apple-data-detectors://3> of Prussia, PA 19406<x-apple-data-detectors://4/0>
Direct: 484-362-0818<tel:484-362-0818> | Mobile: 484-614-4670<tel:484-614-4670> | Fax:610-825-4430<tel:610-825-4430> | Main: 610-825-4000<tel:610-825-4000>
***@***.******@***.***> || www.fmpmedia.com<http://www.fmpmedia.com/>

FMP is an award winning provider of integrated corporate communications solutions including video, webcasting, event production and translation & narration services.
This email and any files transmitted with it are confidential, and may also be legally privileged.  If you are not the intended recipient, you may not review, use, copy, or distribute this message.

On May 5, 2021, at 5:43 PM, Andreas Thomsen ***@***.***> wrote:

﻿

This should be fixed in the next version of the module (V1.0.2), I'll close this for now, please feel free to open it up again if need be.

**Comment by McHauge** [comment]
This is now in the beta builds, and you can get it from the website :)

**Comment by DiViPro01** [comment]
Hi,

I have been testing this, but in all the versions build for avhs, companion doesnt even connect to the hs410

**Comment by McHauge** [comment]
@DiViPro01 Hi, keep in mind that this now requires you to have two plugins installed on the HS410, vs only one before. take a look at the Help.md file for info on the specific plugins, which can be found inside companion via the "?" symbol

**Comment by DiViPro01** [comment]
thanks for the answer! I will try it out as soon as I can
